### ISSUE TITLE
Trivial.Console.Arguments Cannot Parse File System Path

### ISSUE THREAD

**Issue by VaslD** [nuscien/trivial#1]
When I try to use `Arguments` to parse `args` that contains filesystem path (e.g. `install --dir /usr/local/bin`), whichever name/key I use returns empty string.

I also tried defining `Verb`s with properties but they wouldn't work either.

It seems `Arguments` is having trouble with slashes `/`. But I still haven't found the exact code that causes problem.

**Comment by kingcean** [comment]
As you mentioned the value `dir` is empty is because of the slash `/`. The slash `/` is used as the prefix of argument key as same as dash `-`.

```
ipconfig /all
```

![image](https://user-images.githubusercontent.com/1724940/115393006-c9e15c00-a213-11eb-90b3-b701fc7e087f.png)

The way to avoid this issue is to add quotation marks `"` for the value and that style of writing will be more regulated.

```
install --dir "/usr/local/bin"
```

And thanks for your question (issue) suggested, perhaps we need add a feature in next release to support this case that it can pass a path.

**Comment by VaslD** [comment]
Thanks for responding quickly.

I did try all the ways to pass arguments, including quotes (`extract --path "/Users/admin/Desktop`) and using shorthands (`add -f /Volume/C/123.txt`). They did not work, at least on macOS they did not.

I'll try it on a Windows machine after work. And if that fails I'll upload a snippet/screenshot.

**Comment by kingcean** [comment]
I have tested and it can be reproduced. I will fix it soon.

**Comment by VaslD** [comment]
Thank you.

Just curious, how do you plan on interpreting `/` in your fix? I do second your previous comment that there is no telling whether `/usr` is an argument or a path. It may be common sense that anything with more than one `/` in it (`/usr/local`) would look like a path. But how will you treat simple `/p` and `/home`?

**Comment by kingcean** [comment]
- Methods `Get` and `GetFirst` in `Arguments` class have already supported the value with multiple slash `/` now.
- Fixed the issue what it does not work correctly when using quotes.
- A new method `GetFirstOrNext` in `Arguments` class is introduced to get the next parameter when the value of the specific one is empty.

Now you can update the package to 3.7.1 via NuGet to code as following to get the path.

```csharp
var args = new Arguments("install --dir /usr/local/bin");
var path = args.GetFirst("dir").Value; // => /usr/local/bin

args = new Arguments("install --dir \"/usr\"");
path = args.GetFirst("dir").Value; // => /usr

args = new Arguments("install --dir /usr");
path = args.GetFirstOrNext("dir", true).Value; // => /usr
```

The second argument `true` of `GetFirstOrNext` is used to merge the next to `dir` (`{ Key: "dir", Value: "/usr" }`); otherwise, it will return a `Parameter` instance with key `usr` and empty value (`{ Key: "usr", Value: "" }`).
